version: "2.2"
services:

  ###### NODE-RED ######
  nodered:
    image: nodered:v0.0.2 # Name of the built image
    container_name: nodered_33090
    mem_limit: 1500m
    restart: unless-stopped # always restarts (see overview page 12 Industrial Edge Developer Guide)
    environment:
      # Environment variables available at container run-time
      http_proxy: "" # Proxy url's from environment
      https_proxy: ""
      FLOWS: "flow.json"
    volumes: 
     - ./volumeFolder:/data
    logging:
      # allow logging
      options:
        # we use best pactice here as limiting file size and rolling mechanism
        max-size: "10m" # File size is 10MB
        max-file: "2" # only 2 files created before rolling mechanism applies
    ports:
    - "33090:1880"
    networks:
      # define networks connected to container 'data-analytics' 
      proxy-redirect:
        # Name of the network

        ####### NETWORK CONFIG ######
networks:
  # Network interface configuration
  proxy-redirect:
    # Reference 'proxy-redirect' as predefined network
    external:
      # Note: Please create the network manually as it is preexisting on Industrial Edge Device
      name: proxy-redirect
    driver: bridge
